### PR TITLE
fix: don't close modal when clicking inside but dragging outside

### LINKED ISSUE #168: Modal closes when click event starts inside the modal, but ends outside the modal
## Describe the bug
When starting a click inside a modal and end it outside the modal, the modal closes. This should only happen when the click starts outside the modal.

## To Reproduce
- start click inside a modal
- drag outside the modal
- end click
- modal closes

## Expected behavior

Modal doesn't closes when:
- click event starts and ends inside the modal
- click event starts inside the modal, but ends outside the modal

Modal closes when:
- click event starts and ends outside the modal
- click event starts outside the modal, but ends inside the modal

## Screenshots
modalclick

### PR DESCRIPTION
**Pull request by jensCocquyt**
## PR Checklist

This PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] A [changelog entry](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: [168 ](https://github.com/digipolisantwerp/acpaas-ui_angular/issues/168 )

## What is the new behavior?
Modal doesn't close when clicking inside but dragging outside
## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Resolved issues
Fixes #168

### CODE REVIEW

File: packages/layout/lib/src/modal/components/modal-overlay/modal-overlay.component.ts [hunk 1]
```diff
@@ -26,12 +27,21 @@ export class ModalOverlayComponent {
...
+
+	@HostListener('touchend', ['$event'])
+	@HostListener('mouseup', ['$event'])
+	public mouseUpHandler(e: MouseEvent) {
 		const modal = this.ref.nativeElement.querySelector('.m-modal');
 
-		if (modal && (e.target === modal || modal.contains(e.target))) {
+		if ((modal && (e.target === modal || modal.contains(e.target))) || this.mouseDownInsideOverlay) {
 			return;
 		}
```
Comment (jsebrech) [inline packages/layout/lib/src/modal/components/modal-overlay/modal-overlay.component.ts]: het lijkt me dat je in de mouseUp this.mouseDownInsideOverlay op false moet zetten, of anders kan je na een drag in naar uit niet meer naast de modal klikken om die te sluiten.

Comment (jensCocquyt) [reply packages/layout/lib/src/modal/components/modal-overlay/modal-overlay.component.ts]: Hoe bedoel je? Je komt toch altijd eerst in de `mousedown` en dan in `mouseup` handler? En in de `mousedown` wordt hij telkens opnieuw gezet. Ik wil hem wel op false zetten hoor voor de zekerheid, maar lijkt mij niet echt nodig.

Comment (jsebrech) [reply packages/layout/lib/src/modal/components/modal-overlay/modal-overlay.component.ts]: ja, inderdaad, je hebt gelijk
