### PR TITLE
Bugfix/auto complete identical items

### LINKED ISSUE #130: Autocomplete always selects first item if labels are identical
## Describe the bug
When the labels of 2 or more items in the list of the aui-autocomplete component are the same, the result of the onSelect handler will always be the first item, independently of which item is clicked.
The labels are the same because we use a custom template for the aui-selectable-list.

## To Reproduce

1. Implement an aui-autocomplete with a custom template
2. Use the aui-autocomplete component to search for a string and make sure the result is a list where 2 or more items have the same label (but a different visual label in the custom template).
3. Select (click) the second item in the list.
4. The result of the onSelect handler is the first item.

## Expected behavior

The result of the onSelect handler is the item we actually clicked.

## OS (please complete the following information):
 - Version [@acpaas-ui/ngx-components": "2.0.1]

### PR DESCRIPTION
**Pull request by jensCocquyt**
## PR Checklist

This PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] A [changelog entry](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [130](https://github.com/digipolisantwerp/acpaas-ui_angular/issues/130)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Resolved issues
Fixes #130

### CODE REVIEW

File: packages/forms/lib/src/auto-complete/components/auto-complete/auto-complete.component.ts [hunk 1]
```diff
@@ -126,10 +126,8 @@ export class AutoCompleteComponent implements ControlValueAccessor, OnInit, OnCh
...
 
-	public propagateChange(query: string) {
-		const item = this.results.find(res => this.label ? res[this.label] === query : res === query);
-
-		this.query = query;
+	public propagateChange(item: any) {
+		this.query = item !== null ? (this.label ? item[this.label] : item) : '';
 		this.select.emit(item);
 
 		if (!item) {
```
Comment (lievenvg) [inline packages/forms/lib/src/auto-complete/components/auto-complete/auto-complete.component.ts]: Gezien de function nu al meteen gebruik maakt van `item` lijkt het me logischer dat je deze `if` bovenaan zet, niet?
